### ISSUE TITLE
Fix failed tests (ClassNotFoundException: com.splicemachine.spark.splicemachine.ShuffleUtils$)

### ISSUE THREAD

**Issue by jaceklaskowski** [jaceklaskowski/splice-machine-spark-connector#12]
When executing `sbt test` the following exception is reported:

```
[info] - should throw an IllegalStateException when required options (e.g. url) are not defined
[info] splice.v1.SpliceDataSourceV1BatchSpec *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: com/splicemachine/spark/splicemachine/ShuffleUtils$
[info]   at com.splicemachine.spark.splicemachine.SplicemachineContext.insert(SplicemachineContext.scala:459)
[info]   at splice.v1.SpliceRelation.insert(SpliceRelation.scala:32)
[info]   at splice.v1.SpliceDataSourceV1.createRelation(SpliceDataSourceV1.scala:55)
[info]   at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:472)
[info]   at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
[info]   at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
[info]   at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
[info]   at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
[info]   at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
[info]   at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: com.splicemachine.spark.splicemachine.ShuffleUtils$
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[info]   at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:98)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info]   at com.splicemachine.spark.splicemachine.SplicemachineContext.insert(SplicemachineContext.scala:459)
[info]   at splice.v1.SpliceRelation.insert(SpliceRelation.scala:32)
[info]   at splice.v1.SpliceDataSourceV1.createRelation(SpliceDataSourceV1.scala:55)
[info]   at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:472)
[info]   at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
[info]   at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
[info]   ...
```

**Comment by jaceklaskowski** [comment]
Using `sbt 'testOnly splice.v1.SpliceDataSourceV1BatchSpec'` to reproduce.
