### ISSUE TITLE
Using the connector in spark-shell (Spark 2.4.3)

### ISSUE THREAD

**Issue by jaceklaskowski** [jaceklaskowski/splice-machine-spark-connector#6]
It is currently not possible to use the connector in spark-shell as it blows up with NCDF. Please investigate and offer a way to make that possible.

Don't forget to update the `README.md`.

```
$ spark-shell --jars target/scala-2.11/splice-machine-spark-connector_2.11-0.1.jar
...
scala> spark.version
res0: String = 2.4.3

val user = "splice"
val password = "admin"
val url = s"jdbc:splice://localhost:1527/splicedb;user=$user;password=$password"
val table = "t1"
val t1 = spark.read.format("spliceV1").option("url", url).option("table", table).load
java.lang.NoClassDefFoundError: com/splicemachine/spark/splicemachine/SplicemachineContext
  at splice.v1.SpliceDataSourceV1.createRelation(SpliceDataSourceV1.scala:25)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:318)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
  ... 49 elided
Caused by: java.lang.ClassNotFoundException: com.splicemachine.spark.splicemachine.SplicemachineContext
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 54 more
```

**Comment by jaceklaskowski** [comment]
Shouldn't we use `--packages` instead?

**Comment by jaceklaskowski** [comment]
Having a tough fight with maven classifier "machinery" and spark-shell.

splice uses maven classifier for Hadoop distro, e.g. `cdh5.14.0`. spark-shell's `--packages` does not seem to support classifiers (https://issues.apache.org/jira/browse/SPARK-20075). The idea was to include classifier-based deps in `--jars` while the others using `--packages` to cut the necessary deps on the command line.

The strategy does not seem to work though.

In summary:

- hbase_storage uses ZeroCopyLiteralByteString from splice_protocol that extends LiteralByteString from protobuf-java

- so using --jars with hbase_storage and --packages for the others won't work because:

```
Caused by: java.lang.IllegalAccessError: class com.google.protobuf.ZeroCopyLiteralByteString cannot access its superclass com.google.protobuf.LiteralByteString
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at com.splicemachine.si.impl.CoprocessorTxnStore.recordNewTransaction(CoprocessorTxnStore.java:122)
```

**Comment by jaceklaskowski** [comment]
That's the startup command I've been using for tests and eventually gave up because of the error above. Can't seem to find a fix for it.

```
~/dev/oss/spark/bin/spark-shell \
--jars \
target/scala-2.11/splice-machine-spark-connector_2.11-0.1.jar,\
../engine/splice_spark/target/splice_spark-2.8.0.1926-cdh5.14.0.jar,\
../engine/hbase_storage/target/hbase_storage-2.8.0.1926-cdh5.14.0.jar,\
../engine/splice_protocol/target/splice_protocol-2.8.0.1926.jar,\
../engine/hbase_sql/target/hbase_sql-2.8.0.1926-cdh5.14.0.jar,\
~/.ivy2/cache/com.google.protobuf/protobuf-java/bundles/protobuf-java-2.5.0.jar \
--packages \
org.apache.hbase:hbase-client:1.2.0-cdh5.14.0,\
org.apache.hbase:hbase-common:1.2.0-cdh5.14.0,\
org.apache.hbase:hbase-server:1.2.0-cdh5.14.0,\
com.splicemachine:splice_access_api:2.8.0.1926,\
com.splicemachine:splice_machine:2.8.0.1926,\
com.splicemachine:splice_si_api:2.8.0.1926,\
com.splicemachine:splice_timestamp_api:2.8.0.1926,\
com.splicemachine:db-client:2.8.0.1926,\
com.splicemachine:db-engine:2.8.0.1926,\
com.splicemachine:utilities:2.8.0.1926,\
com.splicemachine:pipeline_api:2.8.0.1926,\
com.splicemachine:splice_encoding:2.8.0.1926
```

**Comment by jaceklaskowski** [comment]
Reverting to `--packages` so the following command would work:

```
spark-shell --packages default:splice-machine-spark-connector_2.11:0.1
```

**Comment by jaceklaskowski** [comment]
`--packages` does not work because some dependencies rely on a maven classifier for the Hadoop distro to use, e.g. `cdh5.14.0`.

```
spark-shell --packages default:splice-machine-spark-connector_2.11:0.1
...
:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [download failed: com.splicemachine#splice_spark;2.8.0.1926!splice_spark.jar, download failed: com.splicemachine#hbase_storage;2.8.0.1926!hbase_storage.jar, download failed: com.splicemachine#hbase_sql;2.8.0.1926!hbase_sql.jar, download failed: com.splicemachine#scala_util;2.8.0.1926!scala_util.jar, download failed: com.splicemachine#hbase_pipeline;2.8.0.1926!hbase_pipeline.jar]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1306)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:315)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Think the jar alone is not enough and should include all the deps included, i.e. the jar should rather be an uber-jar.

Let's create an uber-jar (use [sbt-assembly](https://github.com/sbt/sbt-assembly) plugin).

**Comment by jaceklaskowski** [comment]
[sbt-assembly](https://github.com/sbt/sbt-assembly) plugin configured to build the connector (as an uber-jar). The changes are in the [sbt-assembly branch](../tree/sbt-assembly).

When executed in `spark-shell` fails with the same `IllegalAccessError` as before (with `--jars` and `--packages`).

```
$ spark-shell --jars target/scala-2.11/splice-machine-spark-connector-assembly-0.1.jar
...
Caused by: java.lang.IllegalAccessError: class com.google.protobuf.ZeroCopyLiteralByteString cannot access its superclass com.google.protobuf.LiteralByteString
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at com.splicemachine.si.impl.CoprocessorTxnStore.recordNewTransaction(CoprocessorTxnStore.java:122)
  at com.splicemachine.si.impl.ClientTxnLifecycleManager.elevateTransaction(ClientTxnLifecycleManager.java:195)
  at com.splicemachine.si.impl.txn.ReadOnlyTxn.elevateToWritable(ReadOnlyTxn.java:223)
  at com.splicemachine.si.impl.TransactionImpl.doElevate(TransactionImpl.java:357)
  at com.splicemachine.si.impl.TransactionImpl.elevate(TransactionImpl.java:293)
  at com.splicemachine.derby.impl.store.access.SpliceTransaction.elevate(SpliceTransaction.java:114)
  at com.splicemachine.derby.impl.store.access.SpliceTransactionManager.elevate(SpliceTransactionManager.java:1263)
  at com.splicemachine.derby.impl.sql.catalog.SpliceDataDictionary.updateSystemSchemasView(SpliceDataDictionary.java:1371)
  at com.splicemachine.db.impl.sql.catalog.DataDictionaryImpl.boot(DataDictionaryImpl.java:536)
  at com.splicemachine.derby.impl.sql.catalog.SpliceDataDictionary.boot(SpliceDataDictionary.java:476)
  at com.splicemachine.db.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1963)
  at com.splicemachine.db.impl.services.monitor.TopService.bootModule(TopService.java:337)
  at com.splicemachine.db.impl.services.monitor.BaseMonitor.startModule(BaseMonitor.java:546)
  at com.splicemachine.db.impl.services.monitor.FileMonitor.startModule(FileMonitor.java:57)
  at com.splicemachine.db.iapi.services.monitor.Monitor.bootServiceModule(Monitor.java:435)
  at com.splicemachine.db.impl.db.BasicDatabase.boot(BasicDatabase.java:189)
  at com.splicemachine.derby.impl.db.SpliceDatabase.boot(SpliceDatabase.java:120)
  at com.splicemachine.db.impl.services.monitor.BaseMonitor.boot(BaseMonitor.java:1963)
  at com.splicemachine.db.impl.services.monitor.TopService.bootModule(TopService.java:337)
  at com.splicemachine.db.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1798)
  at com.splicemachine.db.impl.services.monitor.BaseMonitor.startProviderService(BaseMonitor.java:1665)
  at com.splicemachine.db.impl.services.monitor.BaseMonitor.findProviderAndStartService(BaseMonitor.java:1543)
  at com.splicemachine.db.impl.services.monitor.BaseMonitor.startPersistentService(BaseMonitor.java:967)
  at com.splicemachine.db.iapi.services.monitor.Monitor.startPersistentService(Monitor.java:557)
  at com.splicemachine.db.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2278)
  ... 66 more
```

**Comment by jaceklaskowski** [comment]
Hmmm...the following does not work either 🤔

```
$ spark-shell --jars target/scala-2.11/splice-machine-spark-connector-assembly-0.1.jar

scala> spark.version
res0: String = 2.4.3

import com.google.protobuf._
ZeroCopyLiteralByteString.wrap(Array.empty[Byte])

scala> ZeroCopyLiteralByteString.wrap(Array.empty[Byte])
java.lang.IllegalAccessError: class com.google.protobuf.ZeroCopyLiteralByteString cannot access its superclass com.google.protobuf.LiteralByteString
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 51 elided
```

**Comment by jaceklaskowski** [comment]
`ZeroCopyLiteralByteString` is a part of `splice_protocol` module. Defining it as a dependency of `spark-shell` does not work either 🤔

```
$ spark-shell --packages com.splicemachine:splice_protocol:2.8.0.1926

import com.google.protobuf._
ZeroCopyLiteralByteString.wrap(Array.empty[Byte])

scala> ZeroCopyLiteralByteString.wrap(Array.empty[Byte])
java.lang.IllegalAccessError: class com.google.protobuf.ZeroCopyLiteralByteString cannot access its superclass com.google.protobuf.LiteralByteString
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 51 elided
```

**Comment by jaceklaskowski** [comment]
Spark 2.4.3 depends on [protobuf-java 2.5.0](https://github.com/apache/spark/blob/v2.4.4/pom.xml#L573-L578) too! It may have been already included in `spark-shell` then. Could this be the root cause (as the classes are in two different classloaders)?!

**Comment by jaceklaskowski** [comment]
Found [this](https://stackoverflow.com/a/50613085/1305344) on StackOverflow that led me to shade netty libs among other things.

With the recent commit, it looks like the connector works fine in `spark-shell` now.
